[package]
name = "axum-http-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5"
hyper = "0.14"
mime = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower = { version = "0.4", features = ["util"] }
tokio = { version = "1", features = ["full"] }
